import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '원숭이 시뮬레이터',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        {/* Google Analytics Script */}
        <meta name='google-site-verification' content='ptwi9qcjNcNSLefzQrJl2MtzMsg_djljtWOYQoRY07k' />
        <Script strategy='afterInteractive' src='https://www.googletagmanager.com/gtag/js?id=G-BF8NW4Z37P' />
        <Script id='google-analytics' strategy='afterInteractive'>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BF8NW4Z37P', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
        <link rel='manifest' href='/manifest.json' />
        <meta name='theme-color' content='#317EFB' />
        <link rel='icon' href='/icons/monkey.png' />
        <link rel='apple-touch-icon' href='/icons/monkey.png' />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white`}>
        {children}
      </body>
    </html>
  );
}
