import type { BossItem, DestinyItem, GachaItem, Item, JobWeaponItem } from './types';

// 강화 무기
export const items: Item[] = [
  // 영웅 무기
  {
    id: 'rocket_launcher',
    name: '로켓 런처',
    description: '폭발하며 불타는 파열을 남기는 폭탄을 목표 지점에 투하합니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher11.gif',
      '/hero/rocket_launcher/rocket_launcher12.gif',
      '/hero/rocket_launcher/rocket_launcher13.gif',
      '/hero/rocket_launcher/rocket_launcher14.gif',
      '/hero/rocket_launcher/rocket_launcher15.gif',
    ],
    damages: [
      { level: 0, damage: 545, cooldown: 84, mana: 35 },
      { level: 1, damage: 545, cooldown: 28, mana: 35 },
      { level: 2, damage: 583, cooldown: 28, mana: 35 },
      { level: 3, damage: 621, cooldown: 28, mana: 35 },
      { level: 4, damage: 665, cooldown: 28, mana: 35 },
      { level: 5, damage: 709, cooldown: 25, mana: 35 },
      { level: 6, damage: 790, cooldown: 25, mana: 35 },
      { level: 7, damage: 916, cooldown: 22, mana: 35 },
      { level: 8, damage: 1079, cooldown: 22, mana: 35 },
      { level: 9, damage: 1199, cooldown: 22, mana: 35 },
      { level: 10, damage: 1379, cooldown: 22, mana: 35 },
      { level: 11, damage: 1504, cooldown: 22, mana: 35 },
      { level: 12, damage: 1700, cooldown: 22, mana: 30 },
      { level: 13, damage: 1897, cooldown: 22, mana: 30 },
      { level: 14, damage: 2385, cooldown: 22, mana: 30 },
      { level: 15, damage: 2998, cooldown: 22, mana: 30 },
    ],
    times: 3,
  },
  {
    id: 'zephyr_dagger',
    name: '제피르',
    description: '공기를 가르는 연속 참격을 펼칩니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger11.gif',
      '/hero/zephyr_dagger/zephyr_dagger12.gif',
      '/hero/zephyr_dagger/zephyr_dagger13.gif',
      '/hero/zephyr_dagger/zephyr_dagger14.gif',
      '/hero/zephyr_dagger/zephyr_dagger15.gif',
    ],
    damages: [
      { level: 0, damage: 446, cooldown: 42, mana: 20 },
      { level: 1, damage: 446, cooldown: 14, mana: 20 },
      { level: 2, damage: 477, cooldown: 14, mana: 20 },
      { level: 3, damage: 508, cooldown: 14, mana: 20 },
      { level: 4, damage: 544, cooldown: 14, mana: 20 },
      { level: 5, damage: 580, cooldown: 12, mana: 20 },
      { level: 6, damage: 647, cooldown: 12, mana: 20 },
      { level: 7, damage: 750, cooldown: 10, mana: 20 },
      { level: 8, damage: 883, cooldown: 10, mana: 22 },
      { level: 9, damage: 981, cooldown: 10, mana: 20 },
      { level: 10, damage: 1128, cooldown: 10, mana: 20 },
      { level: 11, damage: 1231, cooldown: 10, mana: 20 },
      { level: 12, damage: 1392, cooldown: 10, mana: 15 },
      { level: 13, damage: 1552, cooldown: 10, mana: 15 },
      { level: 14, damage: 2029, cooldown: 10, mana: 15 },
      { level: 15, damage: 2551, cooldown: 10, mana: 15 },
    ],
    times: 2,
  },
  {
    id: 'paladin_hammer',
    name: '홀리버스트 해머',
    description: '신성한 망치를 소환해 지면을 내리쳐, 빛의 폭발을 일으킵니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer10.png',
      '/hero/paladin_hammer/paladin_hammer11.gif',
      '/hero/paladin_hammer/paladin_hammer12.gif',
      '/hero/paladin_hammer/paladin_hammer13.gif',
      '/hero/paladin_hammer/paladin_hammer14.gif',
      '/hero/paladin_hammer/paladin_hammer15.gif',
    ],
    damages: [
      { level: 0, damage: 1780, cooldown: 90, mana: 35 },
      { level: 1, damage: 1780, cooldown: 30, mana: 35 },
      { level: 2, damage: 1905, cooldown: 30, mana: 35 },
      { level: 3, damage: 2029, cooldown: 30, mana: 35 },
      { level: 4, damage: 2172, cooldown: 30, mana: 35 },
      { level: 5, damage: 2314, cooldown: 27, mana: 35 },
      { level: 6, damage: 2581, cooldown: 27, mana: 35 },
      { level: 7, damage: 2990, cooldown: 24, mana: 35 },
      { level: 8, damage: 3524, cooldown: 24, mana: 35 },
      { level: 9, damage: 3916, cooldown: 24, mana: 35 },
      { level: 10, damage: 4503, cooldown: 24, mana: 35 },
      { level: 11, damage: 4913, cooldown: 24, mana: 35 },
      { level: 12, damage: 5554, cooldown: 24, mana: 30 },
      { level: 13, damage: 6194, cooldown: 24, mana: 30 },
      { level: 14, damage: 7788, cooldown: 24, mana: 30 },
      { level: 15, damage: 9790, cooldown: 24, mana: 30 },
    ],
    times: 1,
  },
  {
    id: 'shaman_scepter',
    name: '솔라샙터',
    description: '하늘로 솟아올라 폭발적인 태양 광선을 발사하여 적들에게 강력한 피해를 입힙니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter10.png',
      '/hero/shaman_scepter/shaman_scepter11.gif',
      '/hero/shaman_scepter/shaman_scepter12.gif',
      '/hero/shaman_scepter/shaman_scepter13.gif',
      '/hero/shaman_scepter/shaman_scepter14.gif',
      '/hero/shaman_scepter/shaman_scepter15.gif',
    ],
    damages: [
      { level: 0, damage: 102, cooldown: 96, mana: 38 },
      { level: 1, damage: 102, cooldown: 32, mana: 38 },
      { level: 2, damage: 109, cooldown: 32, mana: 38 },
      { level: 3, damage: 116, cooldown: 32, mana: 38 },
      { level: 4, damage: 124, cooldown: 32, mana: 38 },
      { level: 5, damage: 133, cooldown: 29, mana: 38 },
      { level: 6, damage: 148, cooldown: 29, mana: 38 },
      { level: 7, damage: 171, cooldown: 26, mana: 38 },
      { level: 8, damage: 202, cooldown: 26, mana: 38 },
      { level: 9, damage: 224, cooldown: 26, mana: 38 },
      { level: 10, damage: 258, cooldown: 26, mana: 38 },
      { level: 11, damage: 282, cooldown: 26, mana: 38 },
      { level: 12, damage: 318, cooldown: 26, mana: 33 },
      { level: 13, damage: 318, cooldown: 26, mana: 33 },
      { level: 14, damage: 355, cooldown: 26, mana: 33 },
      { level: 15, damage: 446, cooldown: 26, mana: 33 },
    ],
    times: 20,
  },
  {
    id: 'shuriken',
    name: '일루전 슈리켄',
    description: '적을 밀치고 되돌아오는 슈리켄을 투척합니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken11.gif',
      '/hero/shuriken/shuriken12.gif',
      '/hero/shuriken/shuriken13.gif',
      '/hero/shuriken/shuriken14.gif',
      '/hero/shuriken/shuriken15.gif',
    ],
    damages: [
      { level: 0, damage: 686, cooldown: 63, mana: 29 },
      { level: 1, damage: 686, cooldown: 21, mana: 29 },
      { level: 2, damage: 734, cooldown: 21, mana: 29 },
      { level: 3, damage: 784, cooldown: 21, mana: 29 },
      { level: 4, damage: 838, cooldown: 21, mana: 29 },
      { level: 5, damage: 893, cooldown: 19, mana: 29 },
      { level: 6, damage: 997, cooldown: 19, mana: 29 },
      { level: 7, damage: 1149, cooldown: 17, mana: 29 },
      { level: 8, damage: 1347, cooldown: 17, mana: 29 },
      { level: 9, damage: 1498, cooldown: 17, mana: 29 },
      { level: 10, damage: 1717, cooldown: 17, mana: 29 },
      { level: 11, damage: 1872, cooldown: 17, mana: 29 },
      { level: 12, damage: 2109, cooldown: 17, mana: 24 },
      { level: 13, damage: 23512, cooldown: 17, mana: 24 },
      { level: 14, damage: 2949, cooldown: 17, mana: 24 },
      { level: 15, damage: 3707, cooldown: 17, mana: 24 },
    ],
    times: 2,
  },
  {
    id: 'light_half',
    name: '루미에르 하프',
    description: '멜로디로 적을 둔화시키고 폭발로 공중에 띄웁니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half11.gif',
      '/hero/light_half/light_half12.gif',
      '/hero/light_half/light_half13.gif',
      '/hero/light_half/light_half14.gif',
      '/hero/light_half/light_half15.gif',
    ],
    damages: [
      { level: 0, damage: 1630, cooldown: 84, mana: 35 },
      { level: 1, damage: 1630, cooldown: 28, mana: 35 },
      { level: 2, damage: 1744, cooldown: 28, mana: 35 },
      { level: 3, damage: 1858, cooldown: 28, mana: 35 },
      { level: 4, damage: 1989, cooldown: 28, mana: 35 },
      { level: 5, damage: 2119, cooldown: 25, mana: 35 },
      { level: 6, damage: 2364, cooldown: 25, mana: 35 },
      { level: 7, damage: 2738, cooldown: 22, mana: 35 },
      { level: 8, damage: 3227, cooldown: 22, mana: 35 },
      { level: 9, damage: 3586, cooldown: 22, mana: 35 },
      { level: 10, damage: 4124, cooldown: 22, mana: 35 },
      { level: 11, damage: 4499, cooldown: 22, mana: 35 },
      { level: 12, damage: 5086, cooldown: 22, mana: 30 },
      { level: 13, damage: 5672, cooldown: 22, mana: 30 },
      { level: 14, damage: 7131, cooldown: 22, mana: 30 },
      { level: 15, damage: 8965, cooldown: 22, mana: 30 },
    ],
    times: 1,
  },

  // 전설 무기
  {
    id: 'bolt_staff',
    name: '하늘의 제왕, 스톰레온',
    description: '4초 동안 썬더 버드로 변신하여 비행합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff11.gif',
      '/legendary/bolt_staff/bolt_staff12.gif',
      '/legendary/bolt_staff/bolt_staff13.gif',
      '/legendary/bolt_staff/bolt_staff14.gif',
      '/legendary/bolt_staff/bolt_staff15.gif',
    ],
    damages: [
      { level: 0, damage: 1917, cooldown: 84, mana: 35 },
      { level: 1, damage: 1917, cooldown: 28, mana: 35 },
      { level: 2, damage: 2051, cooldown: 28, mana: 35 },
      { level: 3, damage: 2185, cooldown: 28, mana: 35 },
      { level: 4, damage: 2339, cooldown: 28, mana: 35 },
      { level: 5, damage: 2492, cooldown: 25, mana: 35 },
      { level: 6, damage: 2780, cooldown: 25, mana: 35 },
      { level: 7, damage: 3207, cooldown: 22, mana: 35 },
      { level: 8, damage: 3765, cooldown: 22, mana: 35 },
      { level: 9, damage: 4183, cooldown: 22, mana: 35 },
      { level: 10, damage: 4793, cooldown: 22, mana: 35 },
      { level: 11, damage: 5229, cooldown: 22, mana: 35 },
      { level: 12, damage: 5891, cooldown: 22, mana: 30 },
      { level: 13, damage: 6571, cooldown: 22, mana: 30 },
      { level: 14, damage: 8236, cooldown: 22, mana: 30 },
      { level: 15, damage: 10353, cooldown: 22, mana: 30 },
    ],
    times: 1,
  },
  {
    id: 'shiny_sword',
    name: '광휘의 성검, 아르테온',
    description: '대검으로 주변을 크게 베어 근처의 적을 끌어당기고, 뒤로 도약합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword11.gif',
      '/legendary/shiny_sword/shiny_sword12.gif',
      '/legendary/shiny_sword/shiny_sword13.gif',
      '/legendary/shiny_sword/shiny_sword14.gif',
      '/legendary/shiny_sword/shiny_sword15.gif',
    ],
    damages: [
      { level: 0, damage: 800, cooldown: 96, mana: 35 },
      { level: 1, damage: 800, cooldown: 32, mana: 35 },
      { level: 2, damage: 856, cooldown: 32, mana: 35 },
      { level: 3, damage: 912, cooldown: 32, mana: 35 },
      { level: 4, damage: 977, cooldown: 32, mana: 35 },
      { level: 5, damage: 1041, cooldown: 29, mana: 35 },
      { level: 6, damage: 1160, cooldown: 29, mana: 35 },
      { level: 7, damage: 1344, cooldown: 26, mana: 35 },
      { level: 8, damage: 1585, cooldown: 26, mana: 35 },
      { level: 9, damage: 1760, cooldown: 26, mana: 35 },
      { level: 10, damage: 2024, cooldown: 26, mana: 35 },
      { level: 11, damage: 2209, cooldown: 26, mana: 35 },
      { level: 12, damage: 2496, cooldown: 26, mana: 30 },
      { level: 13, damage: 2785, cooldown: 26, mana: 30 },
      { level: 14, damage: 3500, cooldown: 26, mana: 30 },
      { level: 15, damage: 4401, cooldown: 26, mana: 30 },
    ],
    times: 3,
  },
  {
    id: 'twin_sword',
    name: '섬멸의 양날검, 카이엔',
    description: '빠르게 연속 공격을 가한 뒤, 강력한 마무리 일격으로 적을 타격합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword11.gif',
      '/legendary/twin_sword/twin_sword12.gif',
      '/legendary/twin_sword/twin_sword13.gif',
      '/legendary/twin_sword/twin_sword14.gif',
      '/legendary/twin_sword/twin_sword15.gif',
    ],
    damages: [
      { level: 0, damage: 200, cooldown: 132, mana: 40 },
      { level: 1, damage: 200, cooldown: 44, mana: 40 },
      { level: 2, damage: 214, cooldown: 44, mana: 40 },
      { level: 3, damage: 228, cooldown: 44, mana: 40 },
      { level: 4, damage: 244, cooldown: 44, mana: 40 },
      { level: 5, damage: 260, cooldown: 40, mana: 40 },
      { level: 6, damage: 290, cooldown: 40, mana: 40 },
      { level: 7, damage: 336, cooldown: 36, mana: 40 },
      { level: 8, damage: 396, cooldown: 36, mana: 40 },
      { level: 9, damage: 440, cooldown: 36, mana: 40 },
      { level: 10, damage: 506, cooldown: 36, mana: 40 },
      { level: 11, damage: 552, cooldown: 36, mana: 40 },
      { level: 12, damage: 624, cooldown: 36, mana: 35 },
      { level: 13, damage: 696, cooldown: 36, mana: 35 },
      { level: 14, damage: 875, cooldown: 36, mana: 35 },
      { level: 15, damage: 1100, cooldown: 36, mana: 35 },
    ],
    times: 16,
  },
  {
    id: 'scythe_reaper',
    name: '죽음의 사신, 하켄',
    description: '사신의 낫으로 적을 베어 영혼을 흡수합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper11.gif',
      '/legendary/scythe_reaper/scythe_reaper12.gif',
      '/legendary/scythe_reaper/scythe_reaper13.gif',
      '/legendary/scythe_reaper/scythe_reaper14.gif',
      '/legendary/scythe_reaper/scythe_reaper15.gif',
    ],
    damages: [
      { level: 0, damage: 2283, cooldown: 84, mana: 35 },
      { level: 1, damage: 2283, cooldown: 28, mana: 35 },
      { level: 2, damage: 2442, cooldown: 28, mana: 35 },
      { level: 3, damage: 2602, cooldown: 28, mana: 35 },
      { level: 4, damage: 2784, cooldown: 28, mana: 35 },
      { level: 5, damage: 2967, cooldown: 25, mana: 35 },
      { level: 6, damage: 3310, cooldown: 25, mana: 35 },
      { level: 7, damage: 3818, cooldown: 22, mana: 35 },
      { level: 8, damage: 4482, cooldown: 22, mana: 35 },
      { level: 9, damage: 4980, cooldown: 22, mana: 35 },
      { level: 10, damage: 5706, cooldown: 22, mana: 35 },
      { level: 11, damage: 6225, cooldown: 22, mana: 35 },
      { level: 12, damage: 7014, cooldown: 22, mana: 30 },
      { level: 13, damage: 7823, cooldown: 22, mana: 30 },
      { level: 14, damage: 9804, cooldown: 22, mana: 30 },
      { level: 15, damage: 12326, cooldown: 22, mana: 30 },
    ],
    times: 1,
  },
  {
    id: 'phoenix_sword',
    name: '불사의 계약, 이그니스',
    description: '피닉스를 소환해 지면을 활강하며 적들에게 치명적인 화염 피해를 입힙니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword11.gif',
      '/legendary/phoenix_sword/phoenix_sword12.gif',
      '/legendary/phoenix_sword/phoenix_sword13.gif',
      '/legendary/phoenix_sword/phoenix_sword14.gif',
      '/legendary/phoenix_sword/phoenix_sword15.gif',
    ],
    damages: [
      { level: 0, damage: 250, cooldown: 84, mana: 35 },
      { level: 1, damage: 250, cooldown: 28, mana: 35 },
      { level: 2, damage: 268, cooldown: 28, mana: 35 },
      { level: 3, damage: 285, cooldown: 28, mana: 35 },
      { level: 4, damage: 305, cooldown: 28, mana: 35 },
      { level: 5, damage: 324, cooldown: 25, mana: 35 },
      { level: 6, damage: 362, cooldown: 25, mana: 35 },
      { level: 7, damage: 420, cooldown: 22, mana: 35 },
      { level: 8, damage: 494, cooldown: 22, mana: 35 },
      { level: 9, damage: 550, cooldown: 22, mana: 35 },
      { level: 10, damage: 633, cooldown: 22, mana: 35 },
      { level: 11, damage: 689, cooldown: 22, mana: 35 },
      { level: 12, damage: 780, cooldown: 22, mana: 30 },
      { level: 13, damage: 869, cooldown: 22, mana: 30 },
      { level: 14, damage: 1093, cooldown: 22, mana: 30 },
      { level: 15, damage: 1374, cooldown: 22, mana: 30 },
    ],
    times: 9,
  },
  {
    id: 'dragon_bow',
    name: '천룡의 신궁, 드래고니아',
    description: '활에 용의 영혼을 담아 치명적인 관통 화살을 목표를 향해 발사합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow11.gif',
      '/legendary/dragon_bow/dragon_bow12.gif',
      '/legendary/dragon_bow/dragon_bow13.gif',
      '/legendary/dragon_bow/dragon_bow14.gif',
      '/legendary/dragon_bow/dragon_bow15.gif',
    ],
    damages: [
      { level: 0, damage: 2913, cooldown: 114, mana: 35 },
      { level: 1, damage: 2913, cooldown: 38, mana: 35 },
      { level: 2, damage: 3117, cooldown: 38, mana: 35 },
      { level: 3, damage: 3321, cooldown: 38, mana: 35 },
      { level: 4, damage: 3554, cooldown: 38, mana: 35 },
      { level: 5, damage: 3788, cooldown: 34, mana: 35 },
      { level: 6, damage: 4224, cooldown: 34, mana: 35 },
      { level: 7, damage: 4894, cooldown: 30, mana: 35 },
      { level: 8, damage: 5796, cooldown: 30, mana: 35 },
      { level: 9, damage: 6409, cooldown: 30, mana: 35 },
      { level: 10, damage: 7370, cooldown: 30, mana: 35 },
      { level: 11, damage: 8041, cooldown: 30, mana: 35 },
      { level: 12, damage: 9089, cooldown: 30, mana: 30 },
      { level: 13, damage: 10138, cooldown: 30, mana: 30 },
      { level: 14, damage: 12745, cooldown: 30, mana: 30 },
      { level: 15, damage: 16023, cooldown: 30, mana: 30 },
    ],
    times: 1,
  },

  // 필멸 무기
  {
    id: 'terragon_claw',
    name: '지배자, 아케론',
    description: '클로로 앞을 난도질한 후 강렬하게 내려쳐 베어버립니다. 이후 출혈 대미지를 입힙니다.',
    category: 'mortal',
    maxLevel: 15,
    images: [
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw11.gif',
      '/mortal/terragon_claw/terragon_claw12.gif',
      '/mortal/terragon_claw/terragon_claw13.gif',
      '/mortal/terragon_claw/terragon_claw14.gif',
      '/mortal/terragon_claw/terragon_claw15.gif',
    ],
    damages: [
      { level: 0, damage: 373, cooldown: 84, mana: 35 },
      { level: 1, damage: 373, cooldown: 28, mana: 35 },
      { level: 2, damage: 399, cooldown: 28, mana: 35 },
      { level: 3, damage: 424, cooldown: 28, mana: 35 },
      { level: 4, damage: 455, cooldown: 28, mana: 35 },
      { level: 5, damage: 484, cooldown: 25, mana: 35 },
      { level: 6, damage: 540, cooldown: 25, mana: 35 },
      { level: 7, damage: 580, cooldown: 22, mana: 35 },
      { level: 8, damage: 671, cooldown: 22, mana: 35 },
      { level: 9, damage: 746, cooldown: 22, mana: 35 },
      { level: 10, damage: 873, cooldown: 22, mana: 35 },
      { level: 11, damage: 952, cooldown: 22, mana: 35 },
      { level: 12, damage: 1076, cooldown: 22, mana: 30 },
      { level: 13, damage: 1200, cooldown: 22, mana: 30 },
      { level: 14, damage: 1510, cooldown: 22, mana: 30 },
      { level: 15, damage: 1897, cooldown: 22, mana: 30 },
    ],
    times: 7,
  },
  {
    id: 'multi_rocket_launcher',
    name: '초월자, 플레게톤',
    description: '하늘을 가르며 쏟아지는 미사일을 전방을 향해 발사합니다.',
    category: 'mortal',
    maxLevel: 15,
    images: [
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher10.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher11.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher12.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher13.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher14.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher15.gif',
    ],
    damages: [
      { level: 0, damage: 186, cooldown: 135, mana: 35 },
      { level: 1, damage: 186, cooldown: 45, mana: 35 },
      { level: 2, damage: 200, cooldown: 45, mana: 35 },
      { level: 3, damage: 212, cooldown: 45, mana: 35 },
      { level: 4, damage: 227, cooldown: 45, mana: 35 },
      { level: 5, damage: 242, cooldown: 41, mana: 35 },
      { level: 6, damage: 270, cooldown: 41, mana: 35 },
      { level: 7, damage: 290, cooldown: 37, mana: 35 },
      { level: 8, damage: 335, cooldown: 37, mana: 35 },
      { level: 9, damage: 373, cooldown: 37, mana: 35 },
      { level: 10, damage: 436, cooldown: 37, mana: 35 },
      { level: 11, damage: 476, cooldown: 37, mana: 35 },
      { level: 12, damage: 538, cooldown: 37, mana: 30 },
      { level: 13, damage: 600, cooldown: 37, mana: 30 },
      { level: 14, damage: 755, cooldown: 37, mana: 30 },
      { level: 15, damage: 949, cooldown: 37, mana: 30 },
    ],
    times: 20,
  },
  {
    id: 'plasma_gun',
    name: '방랑자, 플레탄',
    description: '전방을 향해 강력한 중력포를 발사합니다.',
    category: 'mortal',
    maxLevel: 15,
    images: ['/mortal/plasma_gun.png'],
    damages: [
      { level: 0, damage: 4308, cooldown: 35, mana: 35 },
      { level: 1, damage: 4308, cooldown: 35, mana: 35 },
      { level: 2, damage: 4308, cooldown: 35, mana: 35 },
      { level: 3, damage: 4308, cooldown: 35, mana: 35 },
      { level: 4, damage: 4308, cooldown: 35, mana: 35 },
      { level: 5, damage: 4308, cooldown: 35, mana: 35 },
      { level: 6, damage: 4308, cooldown: 35, mana: 35 },
      { level: 7, damage: 4308, cooldown: 35, mana: 35 },
      { level: 8, damage: 4847, cooldown: 35, mana: 35 },
      { level: 9, damage: 5385, cooldown: 35, mana: 35 },
      { level: 10, damage: 5924, cooldown: 35, mana: 35 },
      { level: 11, damage: 6462, cooldown: 32, mana: 35 },
      { level: 12, damage: 7001, cooldown: 32, mana: 30 },
      { level: 13, damage: 7809, cooldown: 29, mana: 30 },
      { level: 14, damage: 9424, cooldown: 29, mana: 30 },
      { level: 15, damage: 11848, cooldown: 29, mana: 30 },
    ],
    times: 1,
  },
];

// 열쇠 뽑기 무기
export const gachaItems: GachaItem[] = [
  // 영웅 무기
  {
    id: '1',
    name: '로켓 런처',
    category: 'hero',
    image: '/hero/rocket_launcher/rocket_launcher.png',
  },
  {
    id: '2',
    name: '제피르',
    category: 'hero',
    image: '/hero/zephyr_dagger/zephyr_dagger.png',
  },
  {
    id: '3',
    name: '홀리버스트 해머',
    category: 'hero',
    image: '/hero/paladin_hammer/paladin_hammer.png',
  },
  {
    id: '4',
    name: '솔라샙터',
    category: 'hero',
    image: '/hero/shaman_scepter/shaman_scepter.png',
  },
  {
    id: '5',
    name: '일루전 슈리켄',
    category: 'hero',
    image: '/hero/shuriken/shuriken.png',
  },
  {
    id: '6',
    name: '루미에르 하프',
    category: 'hero',
    image: '/hero/light_half/light_half.png',
  },
  {
    id: '7',
    name: '전설 열쇠',
    category: 'hero',
    image: '/key/desert_ruin_key.png',
  },

  // 전설 무기
  {
    id: '8',
    name: '하늘의 제왕, 스톰레온',
    category: 'legendary',
    image: '/legendary/bolt_staff/bolt_staff.gif',
  },
  {
    id: '9',
    name: '광휘의 성검, 아르테온',
    category: 'legendary',
    image: '/legendary/shiny_sword/shiny_sword.gif',
  },
  {
    id: '10',
    name: '섬멸의 양날검, 카이엔',
    category: 'legendary',
    image: '/legendary/twin_sword/twin_sword.gif',
  },
  {
    id: '11',
    name: '죽음의 사신, 하켄',
    category: 'legendary',
    image: '/legendary/scythe_reaper/scythe_reaper.gif',
  },
  {
    id: '12',
    name: '불사의 계약, 이그니스',
    category: 'legendary',
    image: '/legendary/phoenix_sword/phoenix_sword.gif',
  },
  {
    id: '13',
    name: '천룡의 신궁, 드래고니아',
    category: 'legendary',
    image: '/legendary/dragon_bow/dragon_bow.png',
  },
];

// 직업 무기
export const jobItems: JobWeaponItem[] = [
  {
    id: '메이지',
    image: '/job/mage.png',
    left_cooldown: 1,
    right_cooldown: 8,
    shift_right_cooldown: 18,
    damages: [
      {
        left: [216, 226, 235, 246, 257, 268, 278, 289, 300, 321, 331, 342, 352, 363, 373],
        right: [216, 226, 235, 246, 257, 268, 278, 289, 300, 321, 331, 342, 352, 363, 373],
        shift_right: [2214, 2383, 2552, 2721, 2890, 3060, 3230, 3401, 3571, 3911, 4080, 4250, 4420, 4590, 4760],
      },
    ],
  },
  {
    id: '블레이드',
    image: '/job/ninja.png',
    left_cooldown: 0.8,
    right_cooldown: 8,
    shift_right_cooldown: 18,
    damages: [
      {
        left: [196, 206, 216, 227, 238, 250, 262, 274, 286, 308, 319, 330, 341, 352, 363],
        right: [303, 310, 317, 322, 328, 335, 340, 347, 354, 366, 372, 378, 384, 390, 396],
        shift_right: [2292, 2472, 2652, 2832, 3012, 3192, 3384, 3564, 3744, 4104, 4284, 4476, 4656, 4836, 5016],
      },
    ],
  },
  {
    id: '워리어',
    image: '/job/warrior.png',
    left_cooldown: 1,
    right_cooldown: 8,
    shift_right_cooldown: 18,
    damages: [
      {
        left: [216, 227, 238, 247, 258, 269, 278, 289, 300, 321, 331, 342, 352, 363, 373],
        right: [270, 283, 238, 247, 258, 269, 278, 289, 300, 321, 331, 342, 352, 363, 373],
        shift_right: [2013, 2167, 2310, 2475, 2629, 2783, 2948, 3102, 3256, 3566, 3721, 3876, 4031, 4186, 4341],
      },
    ],
  },
  {
    id: '프로스트',
    image: '/job/lance.png',
    left_cooldown: 1.1,
    right_cooldown: 8,
    shift_right_cooldown: 18,
    damages: [
      {
        left: [262, 272, 283, 294, 305, 316, 326, 337, 348, 370, 381, 392, 403, 414, 425],
        right: [138, 136, 142, 147, 153, 158, 163, 169, 174, 184, 189, 194, 200, 205, 210],
        shift_right: [2013, 2167, 2310, 2475, 2629, 2783, 2948, 3102, 3256, 3566, 3721, 3876, 4031, 4186, 4341],
      },
    ],
  },
];

// 운명 무기
export const destinyItems: DestinyItem[] = [
  {
    id: 'dragon_sword_ef',
    name: '발할라',
    category: 'destiny',
    image: '/destiny/dragon_sword_ef.png',
    damages: [
      {
        left: 1418,
        left_times: 2,
        left_cooldown: 52,
        right: 882,
        right_times: 2,
        right_cooldown: 14,
      },
    ],
  },
  {
    id: 'zeus_spear_ef',
    name: '올림푸스',
    category: 'destiny',
    image: '/destiny/zeus_spear_ef.png',
    damages: [
      {
        left: 3205,
        left_times: 1,
        left_cooldown: 60,
        right: 1099,
        right_times: 2,
        right_cooldown: 19,
      },
    ],
  },
];

// 보스 무기
export const bossItems: BossItem[] = [
  {
    id: 'frozen_staff',
    name: '프로즌 스태프',
    category: 'boss',
    images: ['/boss/frozen_staff.png'],
    damages: [
      {
        level: 0,
        damage: 340,
        cooldown: 90,
        mana: 30,
      },
      {
        level: 1,
        damage: 340,
        cooldown: 30,
        mana: 30,
      },
      {
        level: 2,
        damage: 425,
        cooldown: 30,
        mana: 30,
      },
      {
        level: 3,
        damage: 510,
        cooldown: 30,
        mana: 30,
      },
    ],
    times: 6,
  },
];
