import type { GachaItem, Item } from './types';

export const items: Item[] = [
  // 영웅 무기
  {
    id: 'rocket_launcher',
    name: '로켓 런처',
    description: '폭발하며 불타는 파열을 남기는 폭탄을 목표 지점에 투하합니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher.png',
      '/hero/rocket_launcher/rocket_launcher11.gif',
      '/hero/rocket_launcher/rocket_launcher12.gif',
      '/hero/rocket_launcher/rocket_launcher13.gif',
      '/hero/rocket_launcher/rocket_launcher14.gif',
      '/hero/rocket_launcher/rocket_launcher15.gif',
    ],
  },
  {
    id: 'zephyr_dagger',
    name: '제피르',
    description: '공기를 가르는 연속 참격을 펼칩니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger.png',
      '/hero/zephyr_dagger/zephyr_dagger11.gif',
      '/hero/zephyr_dagger/zephyr_dagger12.gif',
      '/hero/zephyr_dagger/zephyr_dagger13.gif',
      '/hero/zephyr_dagger/zephyr_dagger14.gif',
      '/hero/zephyr_dagger/zephyr_dagger15.gif',
    ],
  },
  {
    id: 'paladin_hammer',
    name: '홀리버스트 해머',
    description: '신성한 망치를 소환해 지면을 내리쳐, 빛의 폭발을 일으킵니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer.png',
      '/hero/paladin_hammer/paladin_hammer10.png',
      '/hero/paladin_hammer/paladin_hammer11.gif',
      '/hero/paladin_hammer/paladin_hammer12.gif',
      '/hero/paladin_hammer/paladin_hammer13.gif',
      '/hero/paladin_hammer/paladin_hammer14.gif',
      '/hero/paladin_hammer/paladin_hammer15.gif',
    ],
  },
  {
    id: 'shaman_scepter',
    name: '솔라샙터',
    description: '하늘로 솟아올라 폭발적인 태양 광선을 발사하여 적들에게 강력한 피해를 입힙니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter.png',
      '/hero/shaman_scepter/shaman_scepter10.png',
      '/hero/shaman_scepter/shaman_scepter11.gif',
      '/hero/shaman_scepter/shaman_scepter12.gif',
      '/hero/shaman_scepter/shaman_scepter13.gif',
      '/hero/shaman_scepter/shaman_scepter14.gif',
      '/hero/shaman_scepter/shaman_scepter15.gif',
    ],
  },
  {
    id: 'shuriken',
    name: '일루전 슈리켄',
    description: '적을 밀치고 되돌아오는 슈리켄을 투척합니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken.png',
      '/hero/shuriken/shuriken11.gif',
      '/hero/shuriken/shuriken12.gif',
      '/hero/shuriken/shuriken13.gif',
      '/hero/shuriken/shuriken14.gif',
      '/hero/shuriken/shuriken15.gif',
    ],
  },
  {
    id: 'light_half',
    name: '루미에르 하프',
    description: '멜로디로 적을 둔화시키고 폭발로 공중에 띄웁니다.',
    category: 'hero',
    maxLevel: 15,
    images: [
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half.png',
      '/hero/light_half/light_half11.gif',
      '/hero/light_half/light_half12.gif',
      '/hero/light_half/light_half13.gif',
      '/hero/light_half/light_half14.gif',
      '/hero/light_half/light_half15.gif',
    ],
  },

  // 전설 무기
  {
    id: 'bolt_staff',
    name: '하늘의 제왕, 스톰레온',
    description: '4초 동안 썬더 버드로 변신하여 비행합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff.gif',
      '/legendary/bolt_staff/bolt_staff11.gif',
      '/legendary/bolt_staff/bolt_staff12.gif',
      '/legendary/bolt_staff/bolt_staff13.gif',
      '/legendary/bolt_staff/bolt_staff14.gif',
      '/legendary/bolt_staff/bolt_staff15.gif',
    ],
  },
  {
    id: 'shiny_sword',
    name: '광휘의 성검, 아르테온',
    description: '대검으로 주변을 크게 베어 근처의 적을 끌어당기고, 뒤로 도약합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword.gif',
      '/legendary/shiny_sword/shiny_sword11.gif',
      '/legendary/shiny_sword/shiny_sword12.gif',
      '/legendary/shiny_sword/shiny_sword13.gif',
      '/legendary/shiny_sword/shiny_sword14.gif',
      '/legendary/shiny_sword/shiny_sword15.gif',
    ],
  },
  {
    id: 'twin_sword',
    name: '섬멸의 양날검, 카이엔',
    description: '빠르게 연속 공격을 가한 뒤, 강력한 마무리 일격으로 적을 타격합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword.gif',
      '/legendary/twin_sword/twin_sword11.gif',
      '/legendary/twin_sword/twin_sword12.gif',
      '/legendary/twin_sword/twin_sword13.gif',
      '/legendary/twin_sword/twin_sword14.gif',
      '/legendary/twin_sword/twin_sword15.gif',
    ],
  },
  {
    id: 'scythe_reaper',
    name: '죽음의 사신, 하켄',
    description: '사신의 낫으로 적을 베어 영혼을 흡수합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper.gif',
      '/legendary/scythe_reaper/scythe_reaper11.gif',
      '/legendary/scythe_reaper/scythe_reaper12.gif',
      '/legendary/scythe_reaper/scythe_reaper13.gif',
      '/legendary/scythe_reaper/scythe_reaper14.gif',
      '/legendary/scythe_reaper/scythe_reaper15.gif',
    ],
  },
  {
    id: 'phoenix_sword',
    name: '불사의 계약, 이그니스',
    description: '피닉스를 소환해 지면을 활강하며 적들에게 치명적인 화염 피해를 입힙니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword.gif',
      '/legendary/phoenix_sword/phoenix_sword11.gif',
      '/legendary/phoenix_sword/phoenix_sword12.gif',
      '/legendary/phoenix_sword/phoenix_sword13.gif',
      '/legendary/phoenix_sword/phoenix_sword14.gif',
      '/legendary/phoenix_sword/phoenix_sword15.gif',
    ],
  },
  {
    id: 'dragon_bow',
    name: '천룡의 신궁, 드래고니아',
    description: '활에 용의 영혼을 담아 치명적인 관통 화살을 목표를 향해 발사합니다.',
    category: 'legendary',
    maxLevel: 15,
    images: [
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow.png',
      '/legendary/dragon_bow/dragon_bow11.gif',
      '/legendary/dragon_bow/dragon_bow12.gif',
      '/legendary/dragon_bow/dragon_bow13.gif',
      '/legendary/dragon_bow/dragon_bow14.gif',
      '/legendary/dragon_bow/dragon_bow15.gif',
    ],
  },

  // 필멸 무기
  {
    id: 'terragon_claw',
    name: '지배자, 아케론',
    description: '클로로 앞을 난도질한 후 강렬하게 내려쳐 베어버립니다. 이후 출혈 대미지를 입힙니다.',
    category: 'mortal',
    maxLevel: 15,
    images: [
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw.png',
      '/mortal/terragon_claw/terragon_claw11.gif',
      '/mortal/terragon_claw/terragon_claw12.gif',
      '/mortal/terragon_claw/terragon_claw13.gif',
      '/mortal/terragon_claw/terragon_claw14.gif',
      '/mortal/terragon_claw/terragon_claw15.gif',
    ],
  },
  {
    id: 'multi_rocket_launcher',
    name: '초월자, 플레게톤',
    description: '하늘을 가르며 쏟아지는 미사일을 전방을 향해 발사합니다.',
    category: 'mortal',
    maxLevel: 15,
    images: [
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher10.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher11.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher12.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher13.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher14.gif',
      '/mortal/multi_rocket_launcher/multi_rocket_launcher15.gif',
    ],
  },
];

export const gachaItems: GachaItem[] = [
  // 영웅 무기
  {
    id: '1',
    name: '로켓 런처',
    category: 'hero',
    image: '/hero/rocket_launcher/rocket_launcher.png',
  },
  {
    id: '2',
    name: '제피르',
    category: 'hero',
    image: '/hero/zephyr_dagger/zephyr_dagger.png',
  },
  {
    id: '3',
    name: '홀리버스트 해머',
    category: 'hero',
    image: '/hero/paladin_hammer/paladin_hammer.png',
  },
  {
    id: '4',
    name: '솔라샙터',
    category: 'hero',
    image: '/hero/shaman_scepter/shaman_scepter.png',
  },
  {
    id: '5',
    name: '일루전 슈리켄',
    category: 'hero',
    image: '/hero/shuriken/shuriken.png',
  },
  {
    id: '6',
    name: '루미에르 하프',
    category: 'hero',
    image: '/hero/light_half/light_half.png',
  },
  {
    id: '7',
    name: '전설 열쇠',
    category: 'hero',
    image: '/key/desert_ruin_key.png',
  },

  // 전설 무기
  {
    id: '8',
    name: '하늘의 제왕, 스톰레온',
    category: 'legendary',
    image: '/legendary/bolt_staff/bolt_staff.gif',
  },
  {
    id: '9',
    name: '광휘의 성검, 아르테온',
    category: 'legendary',
    image: '/legendary/shiny_sword/shiny_sword.gif',
  },
  {
    id: '10',
    name: '섬멸의 양날검, 카이엔',
    category: 'legendary',
    image: '/legendary/twin_sword/twin_sword.gif',
  },
  {
    id: '11',
    name: '죽음의 사신, 하켄',
    category: 'legendary',
    image: '/legendary/scythe_reaper/scythe_reaper.gif',
  },
  {
    id: '12',
    name: '불사의 계약, 이그니스',
    category: 'legendary',
    image: '/legendary/phoenix_sword/phoenix_sword.gif',
  },
  {
    id: '13',
    name: '천룡의 신궁, 드래고니아',
    category: 'legendary',
    image: '/legendary/dragon_bow/dragon_bow.png',
  },
];
